name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.5
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack nugets
      run: | 
        dotnet pack -c Release --no-build AE.CoreWPF/AE.CoreWPF.csproj --output .
        dotnet pack -c Release --no-build AE.CoreWPF.Controls/AE.CoreWPF.Controls.csproj --output .
    - name: Add github source
      run: dotnet nuget add source --username AkiEvansDev --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AkiEvansDev/index.json"
    - name: Push to Git
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.TOKEN_GITHUB }} --source "github" --skip-duplicate
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
